project:
  type: book

book:
  title: "Clinical Programming"
  author: "Qi"
  date: "2024/1/8"
  chapters:
    - index.qmd
    - part: sas\sasprog.qmd
      chapters: 
        - sas\sasprog_process.qmd
        - sas\sasprog_gtl.qmd
    - part: stat\stat.qmd
      chapters: 
        - stat\datamanage.qmd
        - stat\freqanalysis.qmd
        - stat\survivalanalysis.qmd
        - stat\pkanalysis.qmd
    - part: cdisc\cdisc.qmd
      chapters: 
        - cdisc\cdiscae.qmd
        - cdisc\cdiscdm.qmd
        - cdisc\cdiscrs.qmd
        - cdisc\cdisctu.qmd
        - cdisc\cdisctr.qmd


bibliography: references.bib

format:
  html:
    theme: 
      - cosmo
      - custom.scss

editor: visual

