# DM Domain {.cdisc}

+----------+--------------------------------------------------------------------------------------------------------------------------------------------------+
| Variable | Comments                                                                                                                                         |
+==========+==================================================================================================================================================+
| RFXSTDTC | 首次给药日期/时间，如为多周期试验，为第一周期的首次给药日期                                                                                      |
+----------+--------------------------------------------------------------------------------------------------------------------------------------------------+
| RFXENDTC | 末次给药日期/时间，如为多周期试验，为最后一周期的末次给药日期                                                                                    |
+----------+--------------------------------------------------------------------------------------------------------------------------------------------------+
| RFICDTC  | 知情同意日期/时间，如有多次知情同意，取最早的知情同意日期                                                                                        |
+----------+--------------------------------------------------------------------------------------------------------------------------------------------------+
| RFPENDTC | 受试者在研究中的最晚日期/时间。如果受试者最后状态时失访，应取失访前的受试者仍在试验的最晚日期。                                                  |
+----------+--------------------------------------------------------------------------------------------------------------------------------------------------+
| RFSTDTC  | 由sponsor确定，通常为首次给药日期，也可以时随机日期，或者无治疗性的研究，登记日期也可被定义为RFSTDTC。                                           |
+----------+--------------------------------------------------------------------------------------------------------------------------------------------------+
| RFENDTC  | 由sponsor确定，通常为末次给药日期，也可以根据药代动力学特征和半衰期定义一个xx天，RFENDTC=RFXENDTC+XX。                                           |
+----------+--------------------------------------------------------------------------------------------------------------------------------------------------+
| ARM      | ARM/ARMCD必须和TA Domain中相同。                                                                                                                 |
|          |                                                                                                                                                  |
| ARMCD    | 受试者随机且接受用药且计划实际相同：ARM=ACTARM                                                                                                   |
|          |                                                                                                                                                  |
| ACTARM   | 受试者随机且接受用药但计划于实际不同：ARM为随机化分配组别，ACTARM为实际用药组别                                                                  |
|          |                                                                                                                                                  |
| ACTARMCD | 受试者随机化但未接受用药：ARM/ARMCD为随机化组别，ACTARM/ACTARMCD置空                                                                             |
|          |                                                                                                                                                  |
|          | 受试者未随机：ARM/ACTARM置空                                                                                                                     |
+----------+--------------------------------------------------------------------------------------------------------------------------------------------------+
| ARMNRS   | 受试者筛选失败：ARMNRS = SCREEN FAILURE                                                                                                          |
|          |                                                                                                                                                  |
| ACTARMUD | 受试者筛选成功但未随机：ARMNRS = NOT ASSIGNED                                                                                                    |
|          |                                                                                                                                                  |
|          | 受试者随机化但未接受用药：ARMNRS = ASSIGNED, NOT TREATED                                                                                         |
|          |                                                                                                                                                  |
|          | 受试者接受试验用药不是计划的（TA中指定的）：ARMNRS = UNPLANNED TREATMENT，ACTARMUD = 具体的非计划试验用药                                        |
+----------+--------------------------------------------------------------------------------------------------------------------------------------------------+
| COUNTRY  | 研究中心所在的国家代码，如果外国友人在中国参加clinical trials，COUNTRY依旧时中国，他具体的国籍信息放到SC Domain。通常使用ISO3166-1 Alpha-3代码。 |
+----------+--------------------------------------------------------------------------------------------------------------------------------------------------+
|          |                                                                                                                                                  |
+----------+--------------------------------------------------------------------------------------------------------------------------------------------------+
